# lsi: false
# safe: true
# f√∏lgende source declaration giver en fejl, hvis jeg server lokalt
# `realpath': No such file or directory @ realpath_rec - /home/velle/Desktop/osaawebsite/https: (Errno::ENOENT)
#source: "https://github.com/velle/osaawebsite"
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge


url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Open Space Aarhus" # the name of your site, e.g. ACME Corp.
exclude: [gems, node_modules, vendor]
plugins:
  - jekyll-paginate
sass:
    load_paths:
        - _sass
        # - node_modules
        - 3rd_party_code
paginate: 10
paginate_path: "/blog/page:num/"

theme: jekyll-theme-slate